name: ChatSentinel
version: 0.4.0
author: passddos
main: 
description: Anti-Swear/Spam plugin for Spigot
api: "1.13"
api-version: "1.13"
commands:
  chatsentinel:
    description: "Main command for ChatSentinel plugin"
